### ISSUE TITLE
Remove JDK-20 images

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-images#254]
From @zakkak :

> JDK 21 is now out and 23.0 based on JDK 20 is no longer supported (i.e. it doesn't receive any updates):

```yaml
 - graalvm-version: 23.0.1.2-Final
    java-version: 20
    tags: 23.0-java20, 23.0-jdk-20, jdk-20, jdk-20.0.2
    variants:
      - sha: be992959df83beb9f5fe0ffe4606d76b2deba6cb86322b9d3614f09a8a2fbbc8
        arch: amd64
      - sha: e6ed1f76292a5f44bff076225ebbb503b940180b14d6468d8722769ff7eb9e9e
        arch: arm64
```

I haven't implemented it yet, as some previous releases of Quarkus are using these images.
