### ISSUE TITLE
Error: /lib64/libc.so.6: version `GLIBC_x' not found

### ISSUE THREAD

**Issue by SidiBecker** [quarkusio/quarkus-images#285]
After succefully build, when I try to start my native application (at GCP Cloud Run), it fails with:
```
./application: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./application)
./application: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./application)
./application: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./application)
```

I`m building with the command:
```
mvn clean package  -Pnative -Dquarkus.container.image-build=true -Dquarkus.native.container-build=true
```

Same code from yesterday when was working.
Already run `docker builder prune`

Java version: 21.0.6+7-LTS
Mandrel-23.1.6.0-Final
Quarkus version: 3.8.6

/cc
https://github.com/quarkusio/quarkus/issues/46007

**Comment by dcdh** [comment]
Got it too. As a quick fix, need to specify a previous image to make the application worked.

```yaml
quarkus:
  native:
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21@sha256:f74137a6274ddee19ae595202bcfa06008876826549d4f72d6589d8233c55625

```
