### ISSUE TITLE
CI ubi9-quarkus-mandrel-builder-image:devel-latest

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus-images#295]
Refactor our flow here that a GHA periodically pushes new successful builds from https://ci.modcluster.io/view/Mandrel/job/mandrel-master-linux-build-matrix/ to quay.io/quarkusio/ubi9-quarkus-mandrel-builder-image:devel-latest.

**Comment by Karm** [comment]
I'm working with this idea:

mandrel-devel.yaml
```yaml
images:
  - graalvm-version: master
    java-version: NOT_USED
    tags: devel-latest
    variants:
      - sha: NOT_USED
        arch: amd64
      - sha: NOT_USED
        arch: arm64
```

Where `NOT_USED` won't mean the same as null, because the Jenkins API lets you list artifacts, so the BuildAndPush.java can download both .tar.gz and .sha256 and check at least that the download is complete. While obviously not guaranteeing any kind of authenticity of the tarball itself. It blindly trusts anything Jenkins gives it.
